[#13] Obrazci lepše formatirani
ul-fmf/nadlogar pull request #43
Opened 2021-03-21 13:24 UTC by barbara7777

Obrazce formatiramo s pomočjo `django_crispy_forms` in bootstrapa. Poklja se prikažejo čez celo podokno.

2021-03-22 09:43 UTC, jureslak requested changes
Lepo dodano, imam pa nekaj komentarjev:
 - prvi je tak splošen: dodajanje novih paketov je vedno "problematično" v smislu, da potem zastarajo in postanejo nekompatibilni in prinašajo en kup težav. crispy forms so sicer se kar znani, ampak je vseeno treba preveriti pri "ownerjih" projekta, prede delas take velike spremembe.
 - drugi problem je pa, da se v tem projektu uporablja `bulma` kot CSS framework, ti si pa dodala še bootstrap (vem, da za to ker ga potrebuje crispy). To ap skoraj gotovo ni ok, ker imeti dva CSS frameworka, ki se tepeta med sabo povzroča same težave. Tukaj vidim več odločitev: ali res hocemo imeti bulmo ali morda želimo vse prestaviti na bootstrap (potem bi lahko obdržali crispy, ce hocemo), in se, ker je bootstrap vecji, izognili kaksnim problemom v prihodnosti? Ni pa to dovolj dober razlog, z bulmo ni nic narobe, in se da vse narediti brez vecjih tezav - vendar crispy in bootstrap nista primerni orodji.

2021-03-22 09:43 UTC, jureslak commented on nadlogar/static/formstyle.css
> +    width: -webkit-fill-available;
Tole bo delovalo samo na webkit browserjih, treba bi bilo dodati še vsaj `-moz-fill-available` in splošni `fill-available`. Poleg tega je bill `fill-available` preimenovan v `stretch`, ce se prav spomnim, pa še ta je zaenkrat pod experimental. 
 https://developer.mozilla.org/en-US/docs/Web/CSS/width#browser_compatibility

Skoraj gotovo se da to narediti brez experimental featurjev?

2021-03-22 09:43 UTC, jureslak commented on nadlogar/templates/bulma.html
> +</head>
Je tukaj `<head>` že zaprt, potem pa spodaj še enkrat, če prav vidim?

2021-03-22 09:43 UTC, jureslak commented on nadlogar/templates/form.html
> +{% load static %}
Load static bi dal na vrh strani, ker ni res nujno samo del tega blocka. Pri blocku pa manjka `super`, ker bi lahko zdaj ali v prihodnosti v kaksnem drugem templatu v inheritance chainu imeli še kakšen drug content, pa želimo tega samo dodati, ne povoziti.

2021-03-22 09:51 UTC, barbara7777 commented
A, okej. Ja, dodala sem crispy forms, ker se mi je zdelo, da se dosti uporabljajo in da se da tako najlažje narediti, kar sem hotela. Nisem posebej razmišljala, da lahko to prinese težave. Prav, potem je najbrž bolje, da odstranim crispy forms in poskusim isto doseči z bulmo?

2021-03-22 09:53 UTC, jureslak commented
Ja, mislim, da je to najmanj invazivno, če se da brez večjih težav.

2021-03-22 09:55 UTC, matijapretnar commented
Ja, sta dve možnosti. Lahko preostale obrazce napišete z bulno (razen morda generiranih za parametre - za tiste imam v glavi že neko rešitev), lahko pa tudi celotno stran prenesete na Bootstrap, pa vidimo, kaj se bolje obnese.

2021-03-22 10:05 UTC, barbara7777 commented
V redu. Bulme ne poznam, tako da se bom lotila tega, ko bom imela spet malo več časa. Bom najprej poskusila samo tako, brez bootsrapa.

2021-03-22 10:13 UTC, matijapretnar commented
Domenjeno. Morda še to dodam: ni treba, da izbira tipa naloge (generatorja) poteka prek obrazca - lahko gre tudi za malo bolj dodelano stran, na kateri so opisi nalog in podobno.

2021-09-21 04:20 UTC, matijapretnar commented
To je zdaj urejeno.

2021-09-21 04:20 UTC, closed without merging