Dodana navodila za uporabo
ul-fmf/nadlogar pull request #73
Opened 2022-11-17 20:54 UTC by MightyOwler

Dodana osnovna navodila za uporabo Nadlogarja.

2022-11-18 06:37 UTC, matijapretnar requested changes
Aha, vidim, da ste pisali v ločeno datoteko. Ali lahko vsebino združite skupaj s https://github.com/ul-fmf/nadlogar/blob/master/CONTRIBUTING.md?

2022-11-18 08:41 UTC, matijapretnar commented on CONTRIBUTING.md
> +## SMERNICE ZA DODAJANJE NOVIH PROBLEMOV
Tole govori o isti stvari kot odstavek zgoraj. Predlagam, da se zgornjega odnese dol, ker gre za specifično funkcionalnost in je treba najprej povedati, kako se naredi PR.

2022-11-18 08:42 UTC, matijapretnar commented on CONTRIBUTING.md
> +# NAVODILA ZA OSNOVNO UPORABO NADLOGARJA
Po mojem ni treba, da je vse skupaj v velikih začetnicah, itak imamo že `#` in `##`.

2022-11-18 22:07 UTC, zigakmecl commented
Predlagam, da se nekam v navodila nalima še povezavo do originalnih python script [https://github.com/ursa16180/generiranje-nalog/tree/2a7c84f9b4842b7c63136cd2e6b8a68000394576](url)

2022-11-21 08:07 UTC, matijapretnar commented
Glede na to, da se precej navodil nanaša na dodajanje novih besedil, kar bo v kratkem zastarelo, bi najprej uredil #74 in šele nato dokončal #73.

2022-11-21 10:31 UTC, nikerzetic approved these changes
Sledeče je zelo picajzlasta recenzija besedila. Predvsem predlagam nekaj slogovnih popravkov. Brez težav lahko to ignorirate.

2022-11-21 15:21 UTC, MightyOwler commented on README.md
> +Zato ustvarite adminskega uporabnika, kar storite z ukazom `python manage.py createsuperuser`. Ko to storite, vam je dostopen tudi [adminski vmesnik](http://127.0.0.1:8000/admin/), kjer med drugim la
Sem skušal popraviti ``` -> ` v VSC-ju, ampak mi ob shranjevanju avtomatično formatira na eno črtico. Sem pa lokalno popravil tako, da je zdaj lažje kopirati.

2022-11-21 15:31 UTC, MightyOwler commented on CONTRIBUTING.md
> +Ko prek vmesnika dodate besedilo naloge, spremenite podatkovno bazo. Vendar ostane datoteka `nadlogar\problems\fixtures\initial.json` nespremenjena! Zato je treba v terminalu pognati naslednji ukaz (
Tukaj je dejansko mišljeno brez naj, ampak itak bo po pull requestu #74 ta del navodil zastarel in jih bomo odstranili.

2022-11-24 14:50 UTC, matijapretnar approved these changes

2022-11-24 14:52 UTC, merged