Naloge z eksponentno
ul-fmf/nadlogar pull request #82
Opened 2022-12-08 17:35 UTC by MightyOwler

Dodane 3 naloge z eksponentno funkcijo. Naloga z grafom ni narejena v celoti, saj se še nismo do konca zmenili, kako naj stvari izgleda.

2022-12-08 18:15 UTC, MightyOwler commented
Ali naj zaprem ta pull request in odprem novega, kjer sem že formatiral kodo z blackom?

2022-12-09 08:04 UTC, matijapretnar commented
Ne, ni treba odpirati novega, samo popravite tega. Samo dodajte commit, ki vse popravi.

2022-12-09 20:48 UTC, MightyOwler commented
Končno uspelo, nekaj časa je trajalo da sem odpravil vse napake z blackom in flake8.

2022-12-12 08:12 UTC, matijapretnar requested changes

2022-12-12 08:12 UTC, matijapretnar commented on nadlogar/problems/models/eksponentna_funkcija.py
> +class GrafEksponentne(Problem):
Po mojem mora ta naloga počakati, dokler ne rešimo risanja grafov. Sicer se bo npr. pri izbiri tipa nalog vmes pojavljala neka čudna neprebavljena LaTeX koda in bodo ljudje mislili, da je nekaj narobe.

2022-12-12 15:37 UTC, MightyOwler commented
Če prav razumem testi failajo, ker so nekatere migracije ponekod konflikne. Ne razumem pa tega, kako to, da lokalno nimam konfliktov, tukaj pa so, glede na to da sem si povsem posodobil lokalne datoteke

2022-12-15 06:44 UTC, merged